language: node_js
node_js: 
  - "12"

# env:
#   global:
#     - GLOBAL_VAR=
    
cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install -g serverless tslint typescript
  - npm install

script:
  - npm test

# before_deploy:

deploy:
  # Deploys to STG if merged in Master
  - provider: script
    script: scripts/deploy.sh stg
    on:
      tags: false
  # Deploys to PRD if Tag starts with prd-
  - provider: script
    script: scripts/deploy.sh prd
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^prd-.*$

# after_deploy: