language: node_js
node_js: 
  - "12"

# env:
#   global:
#     - GLOBAL_VAR=
    
cache:
  npm: false
  # directories:
  #   - node_modules

install:
  - npm i -g serverless
  - npm i -g typescript
  - npm i -g tslint
  - npm install
  - npm list -g --depth=0

script:
  - npm test

# before_deploy:

deploy:
  # Deploys to STG if merged in Master
  - provider: script
    script: npm run deploy:stg #scripts/deploy.sh stg
    on:
      tags: false
  # Deploys to PRD if Tag starts with prd-
  - provider: script
    script: npm run deploy:prd #scripts/deploy.sh prd
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^prd-.*$

# after_deploy: