language: node_js
node_js: 
  - "12"

# env:
#   global:
#     - GLOBAL_VAR=
    
cache:
  npm: false
  yarn: false
  # directories:
  #   - node_modules

install:
  - yarn install

script:
  - yarn test

# before_deploy:

deploy:
  # Deploys to STG if merged in Master
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh stg #npm run deploy:stg #scripts/deploy.sh stg
    on:
      tags: false
  # Deploys to PRD if Tag starts with prd-
  - provider: script
    skip_cleanup: true
    script: npm run deploy:prd #scripts/deploy.sh prd
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^prd-.*$

# after_deploy: