language: node_js
node_js: 
  - "12"

env:
  global:
    - GLOBAL_VAR=...
    
cache:
  npm: true
  directories:
    - node_modules

install:
  # install dependencies
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - npm install -g serverless
  - npm install

script:
  - npm test
  # run tests

before_deploy:
  #

deploy:
  # Deploys to STG if merged in Master
  - provider: script
    script: scripts/deploy.sh stg
    on:
      tags: false
  - provider: script
    script: scripts/deploy.sh prd
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^prd-.*$

after_deploy:
  #