service: heart-disease
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  # role: arn:aws:iam::458701424327:role/lambda-default-permission
  # vpc: # Optional VPC. But if you use VPC then both subproperties (securityGroupIds and subnetIds) are required
  # securityGroupIds:
  #   - sg-0d2e1db3bdf2b1a05
  # subnetIds:
  #   - subnet-925340bc
  #   - subnet-050c1962
  environment:
    PREDICTOR_URL: ${self:custom.env.predictor.url}
    PREDICTOR_DEV_PORT: ${self:custom.env.predictor.devPort}
plugins:
  - serverless-offline
custom:
  env: ${file(./env/${self:provider.stage}.yml)}
  defaultStage: dev
  profiles:
    dev: default
    prod: default
functions:
  predict:
    handler: dist/src/index.handler
    timeout: 20
    events:
      - http: 
          path: predict
          method: post
          # cors: true
  healthcheck:
    handler: dist/src/index.handler
    events: 
      - http: 
          path: healthcheck
          method: get
          # cors: true